version: 2
updates:
  - package-ecosystem: dotnet-sdk
    directory: /
    schedule:
      interval: weekly
    assignees:
      - jessestricker
    cooldown:
      default-days: 1
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - jessestricker
    cooldown:
      default-days: 1
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    assignees:
      - jessestricker
    cooldown:
      default-days: 1
