name: Release

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  build:
    name: Build
    permissions:
      contents: read
    uses: ./.github/workflows/build.yml

  check-for-release:
    name: Check for release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      bump-type: ${{ steps.get-bump-type.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false
      - name: Install git-cliff
        uses: taiki-e/install-action@5ebac0d9522d786674368e47e92963ba13f2c376 # v2.82.11
        with:
          tool: git-cliff
      - name: Get bump type
        id: get-bump-type
        run: |
          context=$(git-cliff --verbose --unreleased --bump --context)
          bump_type=$(jq --raw-output '.[0].bump_type' <<< "$context")
          echo "value=$bump_type" >> "$GITHUB_OUTPUT"

  release:
    name: Release
    needs: check-for-release
    if: ${{ needs.check-for-release.outputs.bump-type != 'null' }}
    runs-on: windows-latest
    permissions:
      contents: write # to create GitHub release
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
      - name: Restore dependencies
        run: dotnet restore
      - name: Run git-cliff
        uses: orhun/git-cliff-action@f50e11560dce63f7c33227798f90b924471a88b5 # v4.8.0
        id: git-cliff
        with:
          args: --verbose --unreleased --bump --github-repo ${{ github.repository }}
      - name: Publish
        env:
          version: ${{ steps.git-cliff.outputs.version }}
        run: |
          $version = $env:version.TrimStart("v")
          dotnet publish --verbosity normal --runtime win-x64 -p:Version=$version
      - name: Release
        env:
          GH_TOKEN: ${{ github.token }}
          changelog: ${{ steps.git-cliff.outputs.changelog }}
          version: ${{ steps.git-cliff.outputs.version }}
        run: |
          gh release create `
            --fail-on-no-commits `
            --notes-file $env:changelog `
            --title $env:version `
            $env:version `
            artifacts\publish\WindowsThemeSwitcher\release_win-x64\WindowsThemeSwitcher.exe
